### ISSUE TITLE
Add more ways to earn Elite Cookies

### ISSUE THREAD

**Issue by Folas1337** [Meta-Union/Meta-Union#107]
foraging.yml
```yaml
type: block
pools:
  eliteCookieFromForaging:
    base_chance: 0.02
    loot:
      - type: item
        key: elite_spawner_1
        message: "&7[<color:#7a7aff>Reward&7] <color:#dddd63>You got an Elite Cookie!"
```

Another Skript for archaeology:
```
on block drop:
  if event-block = suspicious sand or suspicious gravel:
    execute server command "auraskills:skill item give %player% elite_spawner_1 1"
    send "&7[<#7a7aff>Reward&7] <#dddd63>You got an Elite Cookie!" to player
```
