### ISSUE TITLE
Update servers to 1.21.5

### ISSUE THREAD

**Issue by Folas1337** [Meta-Union/Meta-Union#110]
- [x] Lobby
- [x] Survival
- [ ] Creative

```yaml
Survival:
  To do:
  Has an official update:
  - AxShulkers --> Done
  - Matrix --> Done
  - PvPManager --> Done
  - FancyNpcs --> Done
  - InteractiveBooks --> Done
  Has an unofficial update:
  - ProtocolLib --> Done
  - FreedomChat --> Done
  - Pl3xMap --> Done
  Delete:
  - Skulls
  - Themis
  - QSFindItemAddOn
  - QuickShop-Hikari
```
